//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BattleEnc.rc
//
#define IDC_MYICON                      2
#define IDAPPLY                         3
#define IDC_UNLIMIT_ALL                 3
#define MENU_ITEM_COUNT                 29
#define IDD_BATTLEENC_DIALOG            102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   104
#define IDI_BATTLEENC                   108
#define IDI_SMALL                       109
#define IDC_BATTLEENC                   110
#define IDS_APP_WINDOW_CLASS            111
#define IDR_MAINFRAME                   112
#define IDD_XLIST                       113
#define IDD_SETTINGS                    114
#define IDI_IDLE                        115
#define IDI_ACTIVE                      116
#define IDD_QUESTION                    118
#define IDB_FOLDER                      119
#define IDD_LIST                        119
#define IDC_VERSION                     1000
#define IDC_APP_NAME                    1000
#define IDC_DATETIME                    1001
#define IDC_TARGET_LIST                 1002
#define IDC_EDIT_DEBUG                  1003
#define IDC_EDIT_INFO                   1003
#define IDC_EDITBOX_GPL                 1004
#define IDC_DESCRIPTION                 1005
#define IDC_BUTTON_ENEMY                1006
#define IDC_DESCRIPTION2                1007
#define IDC_ENEMY                       1008
#define IDC_FOE                         1008
#define IDC_BUTTON_FRIEND               1009
#define IDC_FRIEND                      1009
#define IDC_LISTALL_SYS                 1012
#define IDC_RESET_IFF                   1013
#define IDC_TEXT_MSG                    1014
#define IDC_UNFREEZE                    1015
#define IDC_EDIT_TARGET1                1016
#define IDC_EDIT_TARGET2                1017
#define IDC_EDIT_TARGET3                1018
#define IDC_BUTTON_STOP1                1019
#define IDC_BUTTON_STOP2                1020
#define IDC_BUTTON_STOP3                1021
#define IDC_TEXT_PERCENT1               1022
#define IDC_TEXT_PERCENT2               1023
#define IDC_TEXT_PERCENT3               1024
#define IDC_SLIDER1                     1025
#define IDC_SLIDER2                     1026
#define IDC_SLIDER3                     1027
#define IDC_WATCH                       1028
#define IDC_RELOAD                      1029
#define IDC_GROUP1                      1030
#define IDC_GROUP2                      1031
#define IDI_ICON                        1032
#define IDI_ICON2                       1033
#define IDC_EDIT                        1034
#define IDC_THANKS                      1035
#define IDC_MSG1                        1036
#define IDC_MSG2                        1037
#define IDC_HIDE                        1038
#define IDC_SHOW                        1039
#define IDC_EDIT_NOTE                   1040
#define IDC_SHOW_MANUALLY               1041
#define IDC_EDIT_UNIT                   1042
#define IDC_NUKE                        1043
#define IDC_AUTOREFRESH                 1044
#define IDC_SLIDER                      1045
#define IDC_TEXT_PERCENT                1046
#define IDC_SLIDER_BUTTON               1047
#define IDC_GROUPBOX                    1048
#define IDC_SLIDER_Q                    1049
#define IDM_MENU_BASE                   30000
#define IDM_ABOUT                       30000
#define IDM_ABOUT_SHORTCUTS             30001
#define IDM_LIST                        30002
#define IDM_SETTINGS                    30003
#define IDM_STOP                        30004
#define IDM_STOP_FROM_TRAY              30005
#define IDM_REALTIME                    30006
#define IDM_LOGGING                     30007
#define IDM_WATCH                       30008
#define IDM_UNWATCH                     30009
#define IDM_HOMEPAGE                    30010
#define IDM_ONLINEHELP                  30011
#define IDM_UKAGAKA                     30012
#define IDM_SSP                         30013
#define IDM_CROW                        30014
#define IDM_GHOSTCENTER                 30015
#define IDM_CHINESE_S                   30016
#define IDM_CHINESE_T                   30017
#define IDM_ENGLISH                     30018
#define IDM_FINNISH                     30019
#define IDM_FRENCH                      30020
#define IDM_JAPANESE                    30021
#define IDM_SPANISH                     30022
#define IDM_JAPANESEo                   30023
#define IDM_SHOWWINDOW                  30024
#define IDM_EXIT                        30025
#define IDM_EXIT_FROM_TRAY              30026
#define IDM_EXIT_ANYWAY                 30027
#define IDM_SNAP                        30028
#define IDM_LAST_MENU_ITEM              30028
#define IDM_SKIN                        30029
#define IDM_DEBUGPRIVILEGE              30030
#define IDM_MINIMIZE                    30031
#define IDM_ALLOWMORETHAN99             30032
#define IDM_ALLOWMULTI                  30033
#define IDM_ALWAYS_LISTALL              30034
#define IDM_HELP_CMDLINE                30035
#define IDM_WATCH_MULTI                 30036
#define IDM_WATCH_RT8                   30037
#define IDM_WATCH_RT4                   30038
#define IDM_WATCH_RT2                   30039
#define IDM_WATCH_RT_                   30040
#define IDM_WATCH_RT__                  30041
#define IDM_WATCH_RT___                 30042
#define IDM_DISABLE_F1                  30043
#define IDM_LOWER_PRIVILEGE             30044
#define IDM_SHOWWATCHLIST               30045
#define IDM_GSHOW                       35000
#define IDC_COPYRIGHT                   42500
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         30046
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           120
#endif
#endif
